# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acessoPointApp', '0002_auto_20170527_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'feminino'), ('M', 'masculino')], max_length=1, null=True, verbose_name='sexo')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='cpf')),
                ('rg', models.CharField(max_length=20, null=True, verbose_name='rg')),
                ('telefone', models.CharField(max_length=9, null=True, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
