# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessoPointApp', '0003_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='orgao_expedidor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
